# Generated by Django 3.1.3 on 2020-11-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_auto_20201116_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
